import:
  - contexts.yaml

pipelines:
  test-pipeline:
    - task: docker-env
    - task: docker-compose-env
      depends_on: [docker-env]

  pipeline-with-error:
    - task: b

  pipeline-with-args:
    - task: c

  pipeline1:
    - task: a
    - task: c
      depends_on: a
    - task: d
      depends_on: c
    - task: env
      depends_on: c
    - task: e
      depends_on: [c, env]

  pipeline2:
    - task: a
    - task: b
    - task: e
      depends_on: ["a", "b"]

  pipeline3:
    - name: stage1
      task: env
    - name: stage2
      task: env
      depends_on: stage1

  pipeline4:
    - task: f
      allow_failure: true
    - task: a
      depends_on: f

  pipeline5:
    - task: a
      allow_failure: true
    - pipeline: pipeline3
      depends_on: a

tasks:
  docker-env:
    context: alpine-docker
    command:
      - env

  docker-compose-env:
    context: alpine-docker-compose
    command:
      - env
  a:
    command:
      - echo "A"

  b:
    command:
      - ">&2 echo \"error\" && exit 1"

  c:
    command:
      - echo "C - ${ARGS}"

  d:
    command:
      - echo "D"

  e:
    context: alpine-docker
    command:
      - echo "E"
    env:
      AAA: BBB

  f:
    command:
      - ">&2 echo \"error\" && exit 1"

  env:
    command:
      - env

