dist: bin

builds:
  - dir: cmd/eirctl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md
      - autocomplete/bash_completion.bash
      - autocomplete/zsh_completion.zsh

source:
  enabled: true

release:
  prerelease: auto

checksum:
  name_template: checksums.txt

changelog:
  skip: true
