before:
  hooks:
    - go mod download

builds:
- main: ./cmd/taskctl
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
  ignore:
      - goos: darwin
        goarch: 386

checksum:
  name_template: checksums.txt

snapcrafts:
  - name: taskctl
    publish: false
    summary: Software to create fast and easy drum rolls.
    description: This is the best drum roll application out there. Install it and awe!
    confinement: devmode
    grade: devel

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dist: bin

brews:
  - github:
      owner: taskctl
      name: homebrew-taskctl
    commit_author:
      name: Yevhen Terentiev
      email: yevhen.terentiev@gmail.com
    homepage: https://github.com/taskctl/taskctl
