dist: bin

before:
  hooks:
    - go mod download

builds:
- dir: cmd/taskctl
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
  goarm:
    - 6
    - 7
  ignore:
      - goos: darwin
        goarch: 386

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md
      - autocomplete/bash_completion.bash
      - autocomplete/zsh_completion.zsh
      -
release:
  prerelease: auto



checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapcrafts:
  - name: taskctl
    confinement: devmode
    grade: devel
    publish: true
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      amd64: x86_64
      386: i386
    apps:
      taskctl:
        plugs: ["home", "network", "removable-media"]
        completer: autocomplete/bash_completion.bash

brews:
  - github:
      owner: taskctl
      name: homebrew-taskctl
    commit_author:
      name: Yevhen Terentiev
      email: yevhen.terentiev@gmail.com
    homepage: https://github.com/taskctl/taskctl
    install: |
        bin.install "program"
        bash_completion.install "autocomplete/bash_completion.bash"
        zsh_completion.install "autocomplete/zsh_completion.zsh"

dockers:
  - image_templates:
      - "docker.io/taskctl/taskctl:latest"
      - "docker.io/taskctl/taskctl:{{ .Tag }}"
    skip_push: auto

scoop:
  bucket:
    owner: taskctl
    name: scoop-taskctl
  commit_author:
    name: Yevhen Terentiev
    email: yevhen.terentiev@gmail.com
  homepage: https://github.com/taskctl/taskctl

nfpms:
  -
    homepage: https://github.com/taskctl/taskctl
    maintainer: Yevhen Terentiev <yevhen.terentiev@gmail.com>
    description: taskctl - developer's routine tasks automation toolkit. Simple modern alternative to GNU Make 🧰
    formats:
      - deb
      - rpm
