pipelines:
  build:
    - name: Build "darwin"
      task: build
      env:
        GOOS: darwin
        BIN_OUT: bin/taskctl_darwin_amd64
    - name: Build "linux"
      task: build
      env:
        GOOS: linux
        BIN_OUT: bin/taskctl_linux_amd64

  release:
    - task: goimports
    - task: test
      depends_on: goimports
    - task: update-cmd-version
      depends_on: test
    - task: push-tag
      depends_on: update-cmd-version

  lints:
    - task: golint
    - task: govet
      depends_on: golint

  wait:
    - task: golint
#    - task: wait
#      name: wait1
#    - task: wait
#      name: wait2
#    - task: wait
#      name: wait3
#      depends_on: wait2

tasks:
  test:
    command:
      - go test ./...

  build:
    command:
      - GOOS=${GOOS} GOARCH=amd64 go build -o bin/taskctl_${GOOS} ./cmd/taskctl
    variations:
      - GOOS: linux
      - GOOS: darwin
      - GOOS: windows

  update-cmd-version:
    command:
      - sed -i '' '/Version:/s/".*"/"'${ARGS}'"/' cmd/taskctl/cmd.go
      - git add cmd/taskctl/cmd.go

  push-tag:
    command:
      - git commit -m "Release ${ARGS}"
      - git tag ${ARGS}
      - git push origin master
      - git push origin ${ARGS}

  golint:
    command:
      - golint $(go list ./... | grep -v /vendor/)
      - exit 2

  govet:
    command:
      - go vet $(go list ./... | grep -v /vendor/)

  goimports:
    command:
      - goimports -local github.com/taskctl/taskctl -w -format-only ./pkg ./internal ./cmd

  wait:
    command:
      - sleep 10
