pipelines:
  build:
    - name: Build "darwin"
      task: build
      env:
        GOOS: darwin
        BIN_OUT: bin/wilson_darwin_amd64
    - name: Build "linux"
      task: build
      env:
        GOOS: linux
        BIN_OUT: bin/wilson_linux_amd64

  release:
    - task: update-cmd-version
    - task: test
      depends_on: update-cmd-version
    - task: push-tag
      depends_on: test

  lints:
    - task: golint
    - task: govet
      depends_on: golint

tasks:
  test:
    command:
      - go test ./...

  build:
    command:
      - GOOS=${GOOS} GOARCH=amd64 go build -o bin/wilson_${GOOS} ./cmd/wilson
    variations:
      - GOOS: linux
      - GOOS: darwin
      - GOOS: windows

  update-cmd-version:
    command:
      - sed -i '' '/Version:/s/".*"/"'${ARGS}'"/' cmd/wilson/cmd.go
      - git add cmd/wilson/cmd.go

  push-tag:
    command:
      - git commit -m "Release ${ARGS}"
      - git tag ${ARGS}
      - git push origin master
      - git push origin ${ARGS}

  golint:
    command:
      - golint $(go list ./... | grep -v /vendor/)

  govet:
    command:
      - go vet $(go list ./... | grep -v /vendor/)
