name: Release
on: [create]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: |
        GOOS=darwin GOARCH=amd64 go build -o bin/wilson_darwin_amd64 -v .
        GOOS=linux GOARCH=amd64 go build -o bin/wilson_linux_amd64 -v .
        tar cvf - bin/wilson_darwin_amd64 | gzip -n > bin/wilson-darwin-amd64.tar.gz
        tar cvf - bin/wilson_linux_amd64 | gzip -n > bin/wilson-linux-amd64.tar.gz
        sha256sum bin/wilson-darwin-amd64.tar.gz >> bin/checksums.txt
        sha256sum bin/wilson-linux-amd64.tar.gz >> bin/checksums.txt

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/wilson-linux-amd64.tar.gz, bin/wilson-darwin-amd64.tar.gz, bin/checksums.txt"
        token: ${{ secrets.GITHUB_TOKEN }}
