name: Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x

      #- name: Install Snapcraft
      #  uses: samuelmeuli/action-snapcraft@v2
      #  with:
      #    snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}

      #- name: Docker login
      #  uses: azure/docker-login@v2
      #  with:
      #    login-server: 'https://index.docker.io/v1/'
      #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #    password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GOPATH: /home/runner/go

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: taskctl
          path: bin/*