name: Release
on: [create]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: |
        GOOS=darwin GOARCH=amd64 go build -o bin/wilson_darwin_amd64 github.com/trntv/wilson/cmd/wilson
        GOOS=linux GOARCH=amd64 go build -o bin/wilson_linux_amd64 github.com/trntv/wilson/cmd/wilson
        GOOS=windows GOARCH=amd64 go build -o bin/wilson_windows_amd64 github.com/trntv/wilson/cmd/wilson

        GOOS=linux GOARCH=386 go build -o bin/wilson_linux_386 github.com/trntv/wilson/cmd/wilson
        GOOS=windows GOARCH=386 go build -o bin/wilson_windows_386 github.com/trntv/wilson/cmd/wilson

        tar cvf - bin/wilson_darwin_amd64 | gzip -n > bin/wilson-darwin-amd64.tar.gz
        tar cvf - bin/wilson_linux_amd64 | gzip -n > bin/wilson-linux-amd64.tar.gz
        tar cvf - bin/wilson_windows_amd64 | gzip -n > bin/wilson-windows-amd64.tar.gz

        tar cvf - bin/wilson_linux_386 | gzip -n > bin/wilson-linux-386.tar.gz
        tar cvf - bin/wilson_windows_386 | gzip -n > bin/wilson-windows-386.tar.gz

        sha256sum bin/wilson-linux-amd64.tar.gz >> bin/checksums.txt
        sha256sum bin/wilson-windows-amd64.tar.gz >> bin/checksums.txt

        sha256sum bin/wilson-linux-386.tar.gz >> bin/checksums.txt
        sha256sum bin/wilson-windows-386.tar.gz >> bin/checksums.txt
      env:
        GOFLAGS: -ldflags=-s -ldflags=-w

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |-
          bin/wilson_linux_amd64, bin/wilson-linux-amd64.tar.gz,
          bin/wilson_linux_386, bin/wilson-linux-386.tar.gz,
          bin/wilson_darwin_amd64, bin/wilson-linux-amd64.tar.gz,
          bin/wilson_windows_amd64, bin/wilson-windows-amd64.tar.gz,
          bin/wilson_windows_386, bin/wilson-windows-386.tar.gz,
          bin/checksums.txt
        token: ${{ secrets.GITHUB_TOKEN }}
